R1:
  asn: 65101
  ipv4: 172.20.0.1/24
  ipv6: 2001:db8:d::1/64
  prefix_origin: 2001:db8:01::/40 

R2:
  asn: 65102
  ipv4: 172.20.0.2/24
  ipv6: 2001:db8:d::2/64
  prefix_origin: 2001:db8:02::/40 

R3:
  asn: 65103
  ipv4: 172.20.0.3/24
  ipv6: 2001:db8:d::3/64
  prefix_origin: 2001:db8:03::/40 

R4:
  asn: 65104
  ipv4: 172.20.0.4/24
  ipv6: 2001:db8:d::4/64
  prefix_origin: 2001:db8:04::/40 

R5:
  asn: 65105
  ipv4: 172.20.0.5/24
  ipv6: 2001:db8:d::5/64
  prefix_origin: 2001:db8:05::/40 

R6:
  asn: 65106
  ipv4: 172.20.0.6/24
  ipv6: 2001:db8:d::6/64
  prefix_origin: 2001:db8:06::/40 

R7:
  asn: 65107
  ipv4: 172.20.0.7/24
  ipv6: 2001:db8:d::7/64
  prefix_origin: 2001:db8:07::/40 

R8:
  asn: 65108
  ipv4: 172.20.0.8/24
  ipv6: 2001:db8:d::8/64
  prefix_origin: 2001:db8:08::/40 

R9:
  asn: 65109
  ipv4: 172.20.0.9/24
  ipv6: 2001:db8:d::9/64
  prefix_origin: 2001:db8:09::/40 

R10:
  asn: 65110
  ipv4: 172.20.0.10/24
  ipv6: 2001:db8:d::10/64
  prefix_origin: 2001:db8:10::/40 

R11:
  asn: 65111
  ipv4: 172.20.0.11/24
  ipv6: 2001:db8:d::11/64
  prefix_origin: 2001:db8:11::/40 

R12:
  asn: 65112
  ipv4: 172.20.0.12/24
  ipv6: 2001:db8:d::12/64
  prefix_origin: 2001:db8:12::/40 

R13:
  asn: 65113
  ipv4: 172.20.0.13/24
  ipv6: 2001:db8:d::13/64
  prefix_origin: 2001:db8:13::/40 

R14:
  asn: 65114
  ipv4: 172.20.0.14/24
  ipv6: 2001:db8:d::14/64
  prefix_origin: 2001:db8:14::/40 

R15:
  asn: 65115
  ipv4: 172.20.0.15/24
  ipv6: 2001:db8:d::15/64
  prefix_origin: 2001:db8:15::/40 

R16:
  asn: 65116
  ipv4: 172.20.0.16/24
  ipv6: 2001:db8:d::16/64
  prefix_origin: 2001:db8:16::/40 

R17:
  asn: 65117
  ipv4: 172.20.0.17/24
  ipv6: 2001:db8:d::17/64
  prefix_origin: 2001:db8:17::/40 

R18:
  asn: 65118
  ipv4: 172.20.0.18/24
  ipv6: 2001:db8:d::18/64
  prefix_origin: 2001:db8:18::/40 

R19:
  asn: 65119
  ipv4: 172.20.0.19/24
  ipv6: 2001:db8:d::19/64
  prefix_origin: 2001:db8:19::/40 

R20:
  asn: 65120
  ipv4: 172.20.0.20/24
  ipv6: 2001:db8:d::20/64
  prefix_origin: 2001:db8:20::/40 

R21:
  asn: 65121
  ipv4: 172.20.0.21/24
  ipv6: 2001:db8:d::21/64
  prefix_origin: 2001:db8:21::/40 

R22:
  asn: 65122
  ipv4: 172.20.0.22/24
  ipv6: 2001:db8:d::22/64
  prefix_origin: 2001:db8:22::/40 

R23:
  asn: 65123
  ipv4: 172.20.0.23/24
  ipv6: 2001:db8:d::23/64
  prefix_origin: 2001:db8:23::/40 

R24:
  asn: 65124
  ipv4: 172.20.0.24/24
  ipv6: 2001:db8:d::24/64
  prefix_origin: 2001:db8:24::/40 

R25:
  asn: 65125
  ipv4: 172.20.0.25/24
  ipv6: 2001:db8:d::25/64
  prefix_origin: 2001:db8:25::/40 

R26:
  asn: 65126
  ipv4: 172.20.0.26/24
  ipv6: 2001:db8:d::26/64
  prefix_origin: 2001:db8:26::/40 

R27:
  asn: 65127
  ipv4: 172.20.0.27/24
  ipv6: 2001:db8:d::27/64
  prefix_origin: 2001:db8:27::/40 

R28:
  asn: 65128
  ipv4: 172.20.0.28/24
  ipv6: 2001:db8:d::28/64
  prefix_origin: 2001:db8:28::/40 

R29:
  asn: 65129
  ipv4: 172.20.0.29/24
  ipv6: 2001:db8:d::29/64
  prefix_origin: 2001:db8:29::/40 

R30:
  asn: 65130
  ipv4: 172.20.0.30/24
  ipv6: 2001:db8:d::30/64
  prefix_origin: 2001:db8:30::/40 

CPE1:
  ipv4: 172.20.0.101/24
  ipv6: 2001:db8:d::101/64 

CPE2:
  ipv4: 172.20.0.102/24
  ipv6: 2001:db8:d::102/64 

CPE3:
  ipv4: 172.20.0.103/24
  ipv6: 2001:db8:d::103/64 

CPE4:
  ipv4: 172.20.0.104/24
  ipv6: 2001:db8:d::104/64 

CPE5:
  ipv4: 172.20.0.105/24
  ipv6: 2001:db8:d::105/64 

CPE6:
  ipv4: 172.20.0.106/24
  ipv6: 2001:db8:d::106/64 

CPE7:
  ipv4: 172.20.0.107/24
  ipv6: 2001:db8:d::107/64 

CPE8:
  ipv4: 172.20.0.108/24
  ipv6: 2001:db8:d::108/64 

CPE9:
  ipv4: 172.20.0.109/24
  ipv6: 2001:db8:d::109/64 

CPE10:
  ipv4: 172.20.0.110/24
  ipv6: 2001:db8:d::110/64 

CPE11:
  ipv4: 172.20.0.111/24
  ipv6: 2001:db8:d::111/64 

CPE12:
  ipv4: 172.20.0.112/24
  ipv6: 2001:db8:d::112/64 

CPE13:
  ipv4: 172.20.0.113/24
  ipv6: 2001:db8:d::113/64 

CPE14:
  ipv4: 172.20.0.114/24
  ipv6: 2001:db8:d::114/64 

CPE15:
  ipv4: 172.20.0.115/24
  ipv6: 2001:db8:d::115/64 

CPE16:
  ipv4: 172.20.0.116/24
  ipv6: 2001:db8:d::116/64 

CPE17:
  ipv4: 172.20.0.117/24
  ipv6: 2001:db8:d::117/64 

CPE18:
  ipv4: 172.20.0.118/24
  ipv6: 2001:db8:d::118/64 

CPE19:
  ipv4: 172.20.0.119/24
  ipv6: 2001:db8:d::119/64 

CPE20:
  ipv4: 172.20.0.120/24
  ipv6: 2001:db8:d::120/64 

CPE21:
  ipv4: 172.20.0.121/24
  ipv6: 2001:db8:d::121/64 

CPE22:
  ipv4: 172.20.0.122/24
  ipv6: 2001:db8:d::122/64 

CPE23:
  ipv4: 172.20.0.123/24
  ipv6: 2001:db8:d::123/64 

CPE24:
  ipv4: 172.20.0.124/24
  ipv6: 2001:db8:d::124/64 

CPE25:
  ipv4: 172.20.0.125/24
  ipv6: 2001:db8:d::125/64 

CPE26:
  ipv4: 172.20.0.126/24
  ipv6: 2001:db8:d::126/64 

CPE27:
  ipv4: 172.20.0.127/24
  ipv6: 2001:db8:d::127/64 

CPE28:
  ipv4: 172.20.0.128/24
  ipv6: 2001:db8:d::128/64 

CPE29:
  ipv4: 172.20.0.129/24
  ipv6: 2001:db8:d::129/64 

CPE30:
  ipv4: 172.20.0.130/24
  ipv6: 2001:db8:d::130/64 

