---
R1:
 asn: 65101
 ipv4: 172.20.0.1/24
 ipv6: 2001:db8:d::1/64
 prefix_origin: 2001:db8:01::/40

R2:
 asn: 65102
 ipv4: 172.20.0.2/24
 ipv6: 2001:db8:d::2/64
 prefix_origin: 2001:db8:02::/40

R3:
 asn: 65103
 ipv4: 172.20.0.3/24
 ipv6: 2001:db8:d::3/64
 prefix_origin: 2001:db8:03::/40

R4:
 asn: 65104
 ipv4: 172.20.0.4/24
 ipv6: 2001:db8:d::4/64
 prefix_origin: 2001:db8:04::/40

R5:
 asn: 65105
 ipv4: 172.20.0.5/24
 ipv6: 2001:db8:d::5/64
 prefix_origin: 2001:db8:05::/40

R6:
 asn: 65106
 ipv4: 172.20.0.6/24
 ipv6: 2001:db8:d::6/64
 prefix_origin: 2001:db8:06::/40

R7:
 asn: 65107
 ipv4: 172.20.0.7/24
 ipv6: 2001:db8:d::7/64
 prefix_origin: 2001:db8:07::/40

R8:
 asn: 65108
 ipv4: 172.20.0.8/24
 ipv6: 2001:db8:d::8/64
 prefix_origin: 2001:db8:08::/40

R9:
 asn: 65109
 ipv4: 172.20.0.9/24
 ipv6: 2001:db8:d::9/64
 prefix_origin: 2001:db8:09::/40

R10:
 asn: 65110
 ipv4: 172.20.0.10/24
 ipv6: 2001:db8:d::10/64
 prefix_origin: 2001:db8:010::/40

R11:
 asn: 65111
 ipv4: 172.20.0.11/24
 ipv6: 2001:db8:d::11/64
 prefix_origin: 2001:db8:011::/40

R12:
 asn: 65112
 ipv4: 172.20.0.12/24
 ipv6: 2001:db8:d::12/64
 prefix_origin: 2001:db8:012::/40

R13:
 asn: 65113
 ipv4: 172.20.0.13/24
 ipv6: 2001:db8:d::13/64
 prefix_origin: 2001:db8:013::/40

R14:
 asn: 65114
 ipv4: 172.20.0.14/24
 ipv6: 2001:db8:d::14/64
 prefix_origin: 2001:db8:014::/40

R15:
 asn: 65115
 ipv4: 172.20.0.15/24
 ipv6: 2001:db8:d::15/64
 prefix_origin: 2001:db8:015::/40

R16:
 asn: 65116
 ipv4: 172.20.0.16/24
 ipv6: 2001:db8:d::16/64
 prefix_origin: 2001:db8:016::/40

R17:
 asn: 65117
 ipv4: 172.20.0.17/24
 ipv6: 2001:db8:d::17/64
 prefix_origin: 2001:db8:017::/40

R18:
 asn: 65118
 ipv4: 172.20.0.18/24
 ipv6: 2001:db8:d::18/64
 prefix_origin: 2001:db8:018::/40

R19:
 asn: 65119
 ipv4: 172.20.0.19/24
 ipv6: 2001:db8:d::19/64
 prefix_origin: 2001:db8:019::/40

R20:
 asn: 65120
 ipv4: 172.20.0.20/24
 ipv6: 2001:db8:d::20/64
 prefix_origin: 2001:db8:020::/40

R21:
 asn: 65121
 ipv4: 172.20.0.21/24
 ipv6: 2001:db8:d::21/64
 prefix_origin: 2001:db8:021::/40

R22:
 asn: 65122
 ipv4: 172.20.0.22/24
 ipv6: 2001:db8:d::22/64
 prefix_origin: 2001:db8:022::/40

R23:
 asn: 65123
 ipv4: 172.20.0.23/24
 ipv6: 2001:db8:d::23/64
 prefix_origin: 2001:db8:023::/40

R24:
 asn: 65124
 ipv4: 172.20.0.24/24
 ipv6: 2001:db8:d::24/64
 prefix_origin: 2001:db8:024::/40

R25:
 asn: 65125
 ipv4: 172.20.0.25/24
 ipv6: 2001:db8:d::25/64
 prefix_origin: 2001:db8:025::/40

R26:
 asn: 65126
 ipv4: 172.20.0.26/24
 ipv6: 2001:db8:d::26/64
 prefix_origin: 2001:db8:026::/40

R27:
 asn: 65127
 ipv4: 172.20.0.27/24
 ipv6: 2001:db8:d::27/64
 prefix_origin: 2001:db8:027::/40

R28:
 asn: 65128
 ipv4: 172.20.0.28/24
 ipv6: 2001:db8:d::28/64
 prefix_origin: 2001:db8:028::/40

R29:
 asn: 65129
 ipv4: 172.20.0.29/24
 ipv6: 2001:db8:d::29/64
 prefix_origin: 2001:db8:029::/40

R30:
 asn: 65130
 ipv4: 172.20.0.30/24
 ipv6: 2001:db8:d::30/64
 prefix_origin: 2001:db8:030::/40